# Server
server.port=8080

# Jackson: write dates in ISO
spring.jackson.serialization.write-dates-as-timestamps=false

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
